<h1 class="display-1 mb-5">Termos e Condições</h1>

<h2 class="mt-0 mb-4" id="1">Introdução</h2>

<p>Este Site/Campanha utiliza um Serviço prestado pelo CartaoCliente◦com. Por favor tenha em especial atenção que esta Política de Privacidade não é extensível à recolha e uso de informação por parte do promotor desta Campanha de fidelização e/ou outras empresas, registadas em CartaoCliente◦com e que usam o nosso serviço. Ao visitar um site com uma campanha de fidelização de uma destas empresas, tal como este, deverá consultar a política de privacidade da empresa em questão. Poderá encontrar os contactos, termos e mais informação sobre a empresa promotora da Campanha na opção “Contactos” no menu deste site ou no website da empresa promotora da Campanha de fidelização {{$company}}.</p>
<p>Deverá tambeḿ consultar os termos e política de privacidade do serviço CartaoCliente◦com no nosso site (em https://cartaocliente.com/legal).</p>
<p>A presente declaração pode ser atualizada, a qualquer momento, pelo que solicitamos que consulte regularmente a mesma para que se mantenha a par de todas as alterações. Ao utilizar o CartaoCliente◦com ou qualquer Campanha utilizando o seu Serviço, concorda com os presentes termos e com os termos presentes em https://cartaocliente.com/legal.</p>

<h2 class="mt-5 mb-4" id="2">Limitação de responsabilidade</h2>
<p>O Serviço prestado pelo CartaoCliente◦com permite aos Utilizadores registados criarem Campanhas de fidelização para os seus Clientes. Deste modo, o CartaoCliente◦com contém informações indicativas sobre as campanhas de fidelização praticados pelos seus Utilizadores. Esta informação é fornecida pelo Utilizador respectivo, não podendo o CartaoCliente◦com dar qualquer garantia da sua veracidade, actualização ou funcionamento.</p>
<p>O Utilizador (Promotor da Campanha de fidelização) e os Clientes (quem utiliza a campanha do Promotor) entendem e concordam que o CartaoCliente◦com não pode ser responsabilizada por quaisquer danos directos, indirectos, acidentais, especiais, consequenciais ou danos exemplares, incluindo mas não limitados a: (i) danos derivados das regras da Campanha, da não atribuição de pontos ou reclamação de prémios; (ii) danos derivados dos serviços ou produtos inseridos nas campanhas de fidelização; (iii) danos derivados da insatisfação do funcionamento da Campanha de fidelização e/ou pelos serviços prestados; (iv) danos ou outras perdas tangíveis ou intangíveis resultantes da utilização da Campanha; (v) danos derivados das negociações efetuadas entre os Utilizadores e Clientes; (vi) danos derivado do conteúdo, informações incorretas ou que possam ser alteradas pelo Utilizador sem aviso prévio; (vii) danos derivados do cancelamento da campanha, eliminação da mesma ou perda de pontos.</p>
<p>O Utilizador e os Clientes estão cientes que: (i) não há nenhum envolvimento ou intervenção do CartaoCliente◦com nas Campanhas criadas pelo Utilizador, pelo seu conteúdo, pelos negócios entre o Utilizador e os seus Clientes, pelas informações prestadas ou pelas regras aplicadas; (ii) é de sua inteira responsabilidade a confirmação da veracidade e uso das informações prestadas nas Campanhas; (iii) é de inteira responsabilidade do Utilizador a criação da campanha, manutenção, cumprimento dos requisitos legais, aplicação de regras e todo o conteúdo e mecánica relacionado com a mesma; (vi) leram e estão de acordo com os termos e condições presentes.</p>
<p>Em nenhuma situação, nem o CartaoCliente◦com, nem os seus administradores, empresas afiliadas, os prestadores de serviços, distribuidores, diretores e empregados, devem ser responsabilizados por quaisquer danos indiretos, incidentais, especiais, consequentes ou punitivos, incluindo, sem limitação, perda de lucros, dados, uso, boa vontade, ou outras perdas intangíveis resultantes de (i) o acesso do utilizador, utilização ou incapacidade de aceder ao Serviço ou de o utilizar; ii) qualquer conduta ou conteúdo de qualquer terceiro no Serviço; (iii) qualquer conteúdo obtido no Serviço; e (iv) acesso não autorizado, utilização ou alteração das suas transmissões ou conteúdos, seja com base em garantias, contratos, delitos (incluindo negligência) ou qualquer outra teoria jurídica, tenhamos ou não sido informados da possibilidade de tais danos, e mesmo que um recurso aqui estabelecido não tenha cumprido o seu objetivo essencial.</p>

<h2 class="mt-5 mb-4" id="3">Informação recolhida</h2>
<p>Cookies estritamente necessários</p>
<p>Usamos cookies para armazenar informação no seu dispositivo. Este cookies não armazenam qualquer informação pessoal. Tentamos usar apenas os cookies essenciais para prestar o melhor serviço possível.</p>

<h2 class="mt-5 mb-4" id="4">Informação genérica e cookies</h2>
<p>No registo como Utilizador apenas armazenamos o endereço de e-mail para o propósito de iniciar sessão, comunicações essenciais relacionadas com o serviço, e recuperar a palavra-passe. Não iremos vender, alugar ou transmitir estes endereços de email a terceiros. No entanto, tenha em especial atenção que, esta informação, bem como os dados de atribuição de pontos e prémios, é acedida pela empresa promotora desta campanha para gestão da mesma, pelo que aconselhamos veemente que consulte a política de privacidade da empresa em questão, presente na página contactos, no menu deste site, e/ou no site da empresa promotora desta campanha, antes de avançar com o seu registo.</p>
<p>Os visitantes podem registar-se e fazer login no site. No caso da opção “Lembrar palavra-passe” estar ativada aquando do login, um cookie é configurado para ser possível iniciar sessão automaticamente nas próximas vezes que visitar o site.</p>
<p>Através das definições de privacidade do seu browser, é possível escolher os tipos de cookies que podem ser descarregados para o seu dispositivo. Pode aceitar, recusar ou remover cookies através das definições do seu browser, tendo a possibilidade de alterar as permissões.</p>
<p>Aceda à secção “Privacidade” para configurar as preferências de cookies do seu browser ou consulte a área "Ajuda" do browser que utiliza para conhecer os procedimentos a realizar.</p>
<p>Caso opte por desativar cookies pode impedir que alguns serviços funcionem corretamente, afetando, parcial ou totalmente, a navegação no website.</p>
<p>Ao entrar neste website pela primeira vez será solicitado o seu consentimento para a utilização de cookies, conforme descrito nesta declaração, ao continuar a utilizar o website, declara aceitar todos os cookies. Ao utilizar o CartaoCliente◦com, concorda com a recolha e uso das suas informações tal como estabelecido na presente política de privacidade.</p>
<p>A proteção dos seus dados pessoais é muito importante para nós. Se tiver alguma dúvida ou pretende obter mais informações sobre este assunto, contacte-nos: support@cartaocliente.com</p>
